services:
  breachme:
    build:
      context: .
      network: host
    container_name: breachme-lab
    restart: always
    ports:
      - "9001:3000"
    # SECURITY LIMITS
    deploy:
      resources:
        limits:
          memory: 180M
          cpus: '0.3'
    # ISOLATION
    networks:
      - breachme_lab_net
    # PREVENTION: Stops attackers from installing new tools inside the container
    read_only: false # Set to false since SQLite needs to write to vulnerable.db
    tmpfs:
      - /tmp
      - /run

networks:
  breachme_lab_net:
    driver: bridge
    internal: false